### ISSUE TITLE
operations API is not-developer friendly

### ISSUE THREAD

**Issue by theogravity** [anttiviljami/openapi-stack#4]
I have a service that purely does operations without paths, and so it's really odd from a dev experience that the first param must be null because we don't use them.

```
    await client.doOperation(null, {
      ...
    });
```

an ideal experience would probably be

```
    await client.doOperation({
      path: {},
      query: {},
      body: {}
    });
```

where any of those values can be null / undefined

**Comment by anttiviljami** [comment]
Thanks for sharing your design opinion @theogravity. 

The design of `openapi-client-axios` operation method API is derived from the [`axios`](https://axios-http.com/docs/intro) library request API where the first argument always defines the path / url of the request, second parameter is the request body and third parameter additional request config.

Since `operationId` can be directly mapped to an API path and method, we repurpose the first argument for OpenAPI params (in: `path`, `query`, `header`).

In most cases this produces a predicable, nice interface like:

```
await client.getResource(resourceId)
```

```
await client.updateResource(resourceId, payload)
```

But indeed, when there are no path / query params, the call signature ends up looking a bit strange.

```
await client.createResource(null, payload)
```

This is just a side effect of keeping the library simple and predictable though. It's a matter of preference of course. There are lots of OpenAPI code generators that produce similar SDKs interfaces that you suggest. I'd suggest to look elsewhere if you dislike this interface.

**Comment by theogravity** [comment]
Thanks for the very thoughtful response.
